export const contentData = [
  {
    source: 'Meno',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'The unexamined life is not worth living.',
    tags: ['Life', 'Self-Reflection', 'Existence'],
    yearReleased: '380 BC',
  },
  {
    source: 'Meno',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'Knowledge which is acquired under compulsion obtains no hold on the mind.',
    tags: ['Education', 'Learning', 'Compulsion'],
    yearReleased: '380 BC',
  },
  {
    source: 'Meno',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'Virtue, when fully developed, is like a bee, the only thing by which you can produce good things in human affairs as well as in divine.',
    tags: ['Virtue', 'Goodness', 'Ethics'],
    yearReleased: '380 BC',
  },
  {
    source: 'Meno',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'A man cannot search either for what he knows or for what he does not know. He cannot search for what he knows--since he knows it, there is no need to search--nor for what he does not know, for he does not know what to look for.',
    tags: ['Knowledge', 'Ignorance', 'Search'],
    yearReleased: '380 BC',
  },
  {
    source: 'Meno',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'Good actions give strength to ourselves and inspire good actions in others.',
    tags: ['Goodness', 'Action', 'Inspiration'],
    yearReleased: '380 BC',
  },
  {
    source: 'Meno',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'Opinion is the medium between knowledge and ignorance.',
    tags: ['Opinion', 'Knowledge', 'Ignorance'],
    yearReleased: '380 BC',
  },
  {
    source: 'Meno',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'True opinions can prevail only if the facts to which they refer are known; otherwise, they always end in contradiction.',
    tags: ['Opinion', 'Knowledge', 'Contradiction'],
    yearReleased: '380 BC',
  },
  {
    source: 'Meno',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'You are a king by your own fireside, as much as any monarch in his throne.',
    tags: ['Self', 'Empowerment', 'Identity'],
    yearReleased: '380 BC',
  },
  {
    source: 'Meno',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'Education is the kindling of a flame, not the filling of a vessel.',
    tags: ['Education', 'Learning', 'Growth'],
    yearReleased: '380 BC',
  },
  {
    source: 'Meno',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'Inquiry is fatal to certainty.',
    tags: ['Inquiry', 'Certainty', 'Knowledge'],
    yearReleased: '380 BC',
  },
]
