export const contentData = [
  {
    source: 'Phaedo',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'The soul of the philosopher alone sees truth, and the sight is glorious.',
    tags: ['Philosophy', 'Truth', 'Soul'],
    yearReleased: '385 BC',
  },
  {
    source: 'Phaedo',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us.',
    tags: ['Wisdom', 'Self-Reflection', 'Understanding'],
    yearReleased: '385 BC',
  },
  {
    source: 'Phaedo',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'The hour of departure has arrived, and we go our separate ways, I to die, and you to live. Which of these two is better, only God knows.',
    tags: ['Life', 'Death', 'Mystery'],
    yearReleased: '385 BC',
  },
  {
    source: 'Phaedo',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'The body is the tomb of the soul.',
    tags: ['Body', 'Soul', 'Existence'],
    yearReleased: '385 BC',
  },
  {
    source: 'Phaedo',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'Courage is knowing what not to fear.',
    tags: ['Courage', 'Fear', 'Bravery'],
    yearReleased: '385 BC',
  },
  {
    source: 'Phaedo',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'True philosophers are always occupied in the practice of dying.',
    tags: ['Philosophy', 'Death', 'Immortality'],
    yearReleased: '385 BC',
  },
  {
    source: 'Phaedo',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'The soul takes nothing with her to the next world but her education and her culture; and these, it is said, are of the greatest assistance or of the greatest injury to the dead man, at the very beginning of his journey thither.',
    tags: ['Soul', 'Education', 'Culture'],
    yearReleased: '385 BC',
  },
  {
    source: 'Phaedo',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'Death is one of two things. Either it is annihilation, and the dead have no consciousness of anything; or, as we are told, it is really a change: a migration of the soul from one place to another.',
    tags: ['Death', 'Consciousness', 'Existence'],
    yearReleased: '385 BC',
  },
  {
    source: 'Phaedo',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'The soul is immortal, and its future is the most glorious of all futures in the realm of the divine.',
    tags: ['Soul', 'Immortality', 'Divine'],
    yearReleased: '385 BC',
  },
  {
    source: 'Phaedo',
    author: 'Plato',
    category: 'Philosophy',
    quote: 'Those who are wise and who have lived well will return to their native land and live an even better life there.',
    tags: ['Wisdom', 'Virtue', 'Afterlife'],
    yearReleased: '385 BC',
  },
]
